name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t funduk23/cd_docker_project:latest .

      - name: Log in to Docker Hub
        run: |
         docker login -u ${{secrets.DOCKER_USER}} -p ${{secrets.DOCKER_PASS}}

      - name: Push Docker image to Docker Hub
        run: docker push funduk23/cd_docker_project:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/cd_proj
            docker-compose pull
            docker-compose down
            docker-compose up -d
